In [1]:
import os
import os.path
import pandas as pd

In [2]:
# Extract and delete zip files
for j in range (1,4):
    file_name = '20200'+str(j)+'-citibike-tripdata.csv.zip'
    print('Extracting '+file_name)
    os.system('unzip data/'+file_name)
    os.system('rm data/'+file_name)
for i in range (2015,2020):
    for j in range (1,10):
        file_name = str(i)+'0'+str(j)+'-citibike-tripdata.csv.zip'
        print('Extracting '+file_name)
        os.system('unzip data/'+file_name)
        os.system('rm data/'+file_name)
    for j in range(10,13):
        file_name = str(i)+str(j)+'-citibike-tripdata.csv.zip'
        print('Extracting '+file_name)
        os.system('unzip data/'+file_name)
        os.system('rm data/'+file_name)

Extracting 202001-citibike-tripdata.csv.zip
Extracting 202002-citibike-tripdata.csv.zip
Extracting 202003-citibike-tripdata.csv.zip
Extracting 201501-citibike-tripdata.csv.zip
Extracting 201502-citibike-tripdata.csv.zip
Extracting 201503-citibike-tripdata.csv.zip
Extracting 201504-citibike-tripdata.csv.zip
Extracting 201505-citibike-tripdata.csv.zip
Extracting 201506-citibike-tripdata.csv.zip
Extracting 201507-citibike-tripdata.csv.zip
Extracting 201508-citibike-tripdata.csv.zip
Extracting 201509-citibike-tripdata.csv.zip
Extracting 201510-citibike-tripdata.csv.zip
Extracting 201511-citibike-tripdata.csv.zip
Extracting 201512-citibike-tripdata.csv.zip
Extracting 201601-citibike-tripdata.csv.zip
Extracting 201602-citibike-tripdata.csv.zip
Extracting 201603-citibike-tripdata.csv.zip
Extracting 201604-citibike-tripdata.csv.zip
Extracting 201605-citibike-tripdata.csv.zip
Extracting 201606-citibike-tripdata.csv.zip
Extracting 201607-citibike-tripdata.csv.zip
Extracting 201608-citibike-tripdata.csv.zip
Extracting 201609-citibike-tripdata.csv.zip
Extracting 201610-citibike-tripdata.csv.zip
Extracting 201611-citibike-tripdata.csv.zip
Extracting 201612-citibike-tripdata.csv.zip
Extracting 201701-citibike-tripdata.csv.zip
Extracting 201702-citibike-tripdata.csv.zip
Extracting 201703-citibike-tripdata.csv.zip
Extracting 201704-citibike-tripdata.csv.zip
Extracting 201705-citibike-tripdata.csv.zip
Extracting 201706-citibike-tripdata.csv.zip
Extracting 201707-citibike-tripdata.csv.zip
Extracting 201708-citibike-tripdata.csv.zip
Extracting 201709-citibike-tripdata.csv.zip
Extracting 201710-citibike-tripdata.csv.zip
Extracting 201711-citibike-tripdata.csv.zip
Extracting 201712-citibike-tripdata.csv.zip
Extracting 201801-citibike-tripdata.csv.zip
Extracting 201802-citibike-tripdata.csv.zip
Extracting 201803-citibike-tripdata.csv.zip
Extracting 201804-citibike-tripdata.csv.zip
Extracting 201805-citibike-tripdata.csv.zip
Extracting 201806-citibike-tripdata.csv.zip
Extracting 201807-citibike-tripdata.csv.zip
Extracting 201808-citibike-tripdata.csv.zip
Extracting 201809-citibike-tripdata.csv.zip
Extracting 201810-citibike-tripdata.csv.zip
Extracting 201811-citibike-tripdata.csv.zip
Extracting 201812-citibike-tripdata.csv.zip
Extracting 201901-citibike-tripdata.csv.zip
Extracting 201902-citibike-tripdata.csv.zip
Extracting 201903-citibike-tripdata.csv.zip
Extracting 201904-citibike-tripdata.csv.zip
Extracting 201905-citibike-tripdata.csv.zip
Extracting 201906-citibike-tripdata.csv.zip
Extracting 201907-citibike-tripdata.csv.zip
Extracting 201908-citibike-tripdata.csv.zip
Extracting 201909-citibike-tripdata.csv.zip
Extracting 201910-citibike-tripdata.csv.zip
Extracting 201911-citibike-tripdata.csv.zip
Extracting 201912-citibike-tripdata.csv.zip

In [20]:
# move csv files to data dir
os.system('mv *.csv data')

1

In [3]:
for i in range (2015,2017):
    for j in range (1,10):
        file_name = str(i)+'0'+str(j)+'-citibike-tripdata.zip'
        print('Extracting '+file_name)
        os.system('unzip data/'+file_name)
        os.system('rm data/'+file_name)
    for j in range(10,13):
        file_name = str(i)+str(j)+'-citibike-tripdata.zip'
        print('Extracting '+file_name)
        os.system('unzip data/'+file_name)
        os.system('rm data/'+file_name)
os.system('mv *.csv data')

Extracting 201501-citibike-tripdata.zip
Extracting 201502-citibike-tripdata.zip
Extracting 201503-citibike-tripdata.zip
Extracting 201504-citibike-tripdata.zip
Extracting 201505-citibike-tripdata.zip
Extracting 201506-citibike-tripdata.zip
Extracting 201507-citibike-tripdata.zip
Extracting 201508-citibike-tripdata.zip
Extracting 201509-citibike-tripdata.zip
Extracting 201510-citibike-tripdata.zip
Extracting 201511-citibike-tripdata.zip
Extracting 201512-citibike-tripdata.zip
Extracting 201601-citibike-tripdata.zip
Extracting 201602-citibike-tripdata.zip
Extracting 201603-citibike-tripdata.zip
Extracting 201604-citibike-tripdata.zip
Extracting 201605-citibike-tripdata.zip
Extracting 201606-citibike-tripdata.zip
Extracting 201607-citibike-tripdata.zip
Extracting 201608-citibike-tripdata.zip
Extracting 201609-citibike-tripdata.zip
Extracting 201610-citibike-tripdata.zip
Extracting 201611-citibike-tripdata.zip
Extracting 201612-citibike-tripdata.zip

1

In [2]:
j=1
init_file_name = '20200'+str(j)+'-citibike-tripdata.csv'
init_file_path = 'data/'+init_file_name
temp_df = pd.read_csv(init_file_path, nrows=10)
bike_df = temp_df
init_cols = temp_df.columns

In [3]:
# Test gathering csvs
path_to_search = os.path.abspath("data/")
the_same_bool = True
for files in os.walk(str(path_to_search)):
    for file in files[2]:
        if (the_same_bool)&(file!=init_file_name):
            #print (file)
            temp_df = pd.read_csv('data/'+file, nrows = 10)
            cols = temp_df.columns
            if len(cols)!=len(init_cols):
                the_same_bool = False
            else:
                for j in range(0,len(cols)):
                    if cols[j]!=init_cols[j]:
                        the_same_bool = False
            if not(the_same_bool):
                print(cols)
                print(init_cols)
                dict = {}
                for j in range(0,len(cols)):
                    dict[cols[j]] = init_cols[j]
                temp_df = temp_df.rename(columns=dict)
                bike_df=bike_df.append(temp_df, ignore_index=True)
                #print('---------------------')
                the_same_bool = True
            else:
                bike_df=bike_df.append(temp_df, ignore_index=True)

In [4]:
init_cols=temp_df.columns
for j in range(0,len(init_cols)):
    print(str(j)+' '+init_cols[j])
temp_df.head()

0 tripduration
1 starttime
2 stoptime
3 start station id
4 start station name
5 start station latitude
6 start station longitude
7 end station id
8 end station name
9 end station latitude
10 end station longitude
11 bikeid
12 usertype
13 birth year
14 gender

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1589,2020-03-01 00:00:03.6400,2020-03-01 00:26:32.9860,224,Spruce St & Nassau St,40.711464,-74.005524,3574,Prospect Pl & Underhill Ave,40.676969,-73.965790,16214,Subscriber,1980,1
1,389,2020-03-01 00:00:16.7560,2020-03-01 00:06:46.0620,293,Lafayette St & E 8 St,40.730207,-73.991026,223,W 13 St & 7 Ave,40.737815,-73.999947,29994,Subscriber,1991,2
2,614,2020-03-01 00:00:20.0580,2020-03-01 00:10:34.2200,379,W 31 St & 7 Ave,40.749156,-73.991600,515,W 43 St & 10 Ave,40.760094,-73.994618,39853,Subscriber,1991,1
3,597,2020-03-01 00:00:24.3510,2020-03-01 00:10:22.3390,3739,Perry St & Greenwich Ave,40.735918,-74.000939,325,E 19 St & 3 Ave,40.736245,-73.984738,42608,Subscriber,1989,1
4,1920,2020-03-01 00:00:26.1120,2020-03-01 00:32:26.2680,236,St Marks Pl & 2 Ave,40.728419,-73.987140,3124,46 Ave & 5 St,40.747310,-73.954510,36288,Subscriber,1993,1

In [5]:
def date_sub(date_str):
    return date_str[:7]
temp_df['starttime']=temp_df['starttime'].apply(date_sub)
temp_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1589,2020-03,2020-03-01 00:26:32.9860,224,Spruce St & Nassau St,40.711464,-74.005524,3574,Prospect Pl & Underhill Ave,40.676969,-73.965790,16214,Subscriber,1980,1
1,389,2020-03,2020-03-01 00:06:46.0620,293,Lafayette St & E 8 St,40.730207,-73.991026,223,W 13 St & 7 Ave,40.737815,-73.999947,29994,Subscriber,1991,2
2,614,2020-03,2020-03-01 00:10:34.2200,379,W 31 St & 7 Ave,40.749156,-73.991600,515,W 43 St & 10 Ave,40.760094,-73.994618,39853,Subscriber,1991,1
3,597,2020-03,2020-03-01 00:10:22.3390,3739,Perry St & Greenwich Ave,40.735918,-74.000939,325,E 19 St & 3 Ave,40.736245,-73.984738,42608,Subscriber,1989,1
4,1920,2020-03,2020-03-01 00:32:26.2680,236,St Marks Pl & 2 Ave,40.728419,-73.987140,3124,46 Ave & 5 St,40.747310,-73.954510,36288,Subscriber,1993,1

In [6]:
useful_cols_idx = [0,1,3,5,6,13,14]
init_cols[useful_cols_idx]

Index(['tripduration', 'starttime', 'start station id',
       'start station latitude', 'start station longitude', 'birth year',
       'gender'],
      dtype='object')

In [7]:
# # Gather csvs
# #number_of_rows = 1000

# j=1
# init_file_name = '20200'+str(j)+'-citibike-tripdata.csv'
# init_file_path = 'data/'+init_file_name
# temp_df = pd.read_csv(init_file_path, usecols=init_cols[useful_cols_idx])
# temp_df[init_cols[1]]=temp_df[init_cols[1]].apply(date_sub)
# bike_df = temp_df

# path_to_search = os.path.abspath("data/")
# the_same_bool = True
# for files in os.walk(str(path_to_search)):
#     for file in files[2]:
#         if (the_same_bool)&(file!=init_file_name):
#             print (file)
#             try:
#                 temp_df = pd.read_csv('data/'+file, usecols=init_cols[useful_cols_idx])
#             except:
#                 temp_df = pd.read_csv('data/'+file, nrows = 10)
#                 cols = temp_df.columns
#                 temp_df = pd.read_csv('data/'+file, usecols=cols[useful_cols_idx])
#             bike_df=bike_df.append(temp_df, ignore_index=True)

In [8]:
# Gather csvs
#number_of_rows = 1000

useful_cols_idx = [0,1,3,5,6,13,14]
print(init_cols[useful_cols_idx])

j=1
init_file_name = '20200'+str(j)+'-citibike-tripdata.csv'
init_file_path = 'data/'+init_file_name
temp_df = pd.read_csv(init_file_path, usecols=init_cols[useful_cols_idx])
temp_df[init_cols[1]]=temp_df[init_cols[1]].apply(date_sub)
temp_df = temp_df.dropna()
bike_df = temp_df
bike_df.astype({'tripduration': 'int'}).dtypes
bike_df.astype({'start station id': 'int'}).dtypes
bike_df.astype({'birth year': 'int'}).dtypes
bike_df.astype({'gender': 'int'}).dtypes
temp_df.head()

Index(['tripduration', 'starttime', 'start station id',
       'start station latitude', 'start station longitude', 'birth year',
       'gender'],
      dtype='object')

,tripduration,starttime,start station id,start station latitude,start station longitude,birth year,gender
0,789,2020-01,504,40.732219,-73.981656,1992,1
1,1541,2020-01,3423,40.661063,-73.979453,1969,1
2,1464,2020-01,3687,40.743227,-73.974498,1963,1
3,592,2020-01,346,40.736529,-74.006180,1980,1
4,702,2020-01,372,40.694546,-73.958014,1982,1

In [9]:
the_same_bool = True
for files in os.walk(str(path_to_search)):
    for file in files[2]:
        if (file!=init_file_name):
            print (file)
            temp_df = pd.read_csv('data/'+file, nrows = 1)
            cols = temp_df.columns
            if len(cols)!=len(init_cols):
                the_same_bool = False
            else:
                for j in range(0,len(cols)):
                    if cols[j]!=init_cols[j]:
                        the_same_bool = False
            if not(the_same_bool):
                temp_df = pd.read_csv('data/'+file, cols[useful_cols_idx], engine='python', encoding='utf-8', error_bad_lines=False)
                temp_df.astype({'tripduration': 'int'}).dtypes
                temp_df.astype({'start station id': 'int'}).dtypes
                temp_df.astype({'birth year': 'int'}).dtypes
                temp_df.astype({'gender': 'int'}).dtypes
#                print(cols)
#                print(init_cols)
                dict = {}
                for j in range(0,len(useful_cols_idx)):
                    dict[cols[useful_cols_idx[j]]] = init_cols[useful_cols_idx[j]]
                temp_df = temp_df.rename(columns=dict)
                temp_df = temp_df.dropna()
                temp_df[init_cols[1]]=temp_df[init_cols[1]].apply(date_sub)
                temp_df.astype({'tripduration': 'int'}).dtypes
                temp_df.astype({'start station id': 'int'}).dtypes
                temp_df.astype({'birth year': 'int'}).dtypes
                temp_df.astype({'gender': 'int'}).dtypes
                bike_df=bike_df.append(temp_df)
#                print('---------------------')
                the_same_bool = True
            else:
#                print(cols[useful_cols_idx])
                temp_df = pd.read_csv('data/'+file, usecols=cols[useful_cols_idx], engine='python', encoding='utf-8', error_bad_lines=False)
                temp_df = temp_df.dropna()
                temp_df[init_cols[1]]=temp_df[init_cols[1]].apply(date_sub)
                temp_df.astype({'tripduration': 'int'}).dtypes
                temp_df.astype({'start station id': 'int'}).dtypes
                temp_df.astype({'birth year': 'int'}).dtypes
                temp_df.astype({'gender': 'int'}).dtypes
                bike_df=bike_df.append(temp_df)
                bike_df=bike_df.append(temp_df, ignore_index=True)

201904-citibike-tripdata.csv

Skipping line 301146: unexpected end of data

201905-citibike-tripdata.csv
201906-citibike-tripdata.csv
201907-citibike-tripdata.csv

Skipping line 476492: unexpected end of data

201908-citibike-tripdata.csv

Skipping line 490481: unexpected end of data

201909-citibike-tripdata.csv
201910-citibike-tripdata.csv
201911-citibike-tripdata.csv
201912-citibike-tripdata.csv
202002-citibike-tripdata.csv
202003-citibike-tripdata.csv

In [11]:
bike_df.to_csv('gathered_bike_data.csv',index=False)